behaviors:
  ai-tank-01:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64 # todo: check tensorboard and adjust this
    summary_freq: 10000
  ai-tank-02:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: Demo/Demo.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: Demo/Demo.demo
    max_steps: 500000
    time_horizon: 64 # todo: check tensorboard and adjust this
    summary_freq: 10000
engine_settings:
  no_graphics: false
checkpoint_settings:
  run_id: assignment-01-2024-11-08
  force: true
